"""add_location_id_to_menu

Revision ID: bc38c81ada05
Revises: 60038b5d0424
Create Date: 2025-12-31 21:46:21.001830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc38c81ada05'
down_revision: Union[str, Sequence[str], None] = '60038b5d0424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete existing data since we're changing the schema
    # This is safe for development - production would need proper data migration
    op.execute("DELETE FROM itemphoto")
    op.execute("DELETE FROM itemdietarytaglink")
    op.execute("DELETE FROM itemallergenlink")
    op.execute("DELETE FROM item")
    op.execute("DELETE FROM category")
    op.execute("DELETE FROM menu")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('location_id', sa.Uuid(), nullable=False))
    op.alter_column('menu', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_menu_org_id'), table_name='menu')
    op.create_index(op.f('ix_menu_location_id'), 'menu', ['location_id'], unique=False)
    op.drop_constraint(op.f('menu_org_id_fkey'), 'menu', type_='foreignkey')
    op.create_foreign_key(None, 'menu', 'location', ['location_id'], ['id'])
    op.drop_column('menu', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.create_foreign_key(op.f('menu_org_id_fkey'), 'menu', 'organization', ['org_id'], ['id'])
    op.drop_index(op.f('ix_menu_location_id'), table_name='menu')
    op.create_index(op.f('ix_menu_org_id'), 'menu', ['org_id'], unique=False)
    op.alter_column('menu', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('menu', 'location_id')
    # ### end Alembic commands ###
